### ISSUE TITLE
提示TypeError: object of type 'Tensor' has no len()

### ISSUE THREAD

**Issue by zyjia** [sherlockchou86/vision-web-service#1]
Traceback (most recent call last):
  File "server.py", line 10, in <module>
    import vision
  File "/home/tonyzhang/data/python/vision-web-service/vision/__init__.py", line 224, in <module>
    yolo = YOLO()
  File "/home/tonyzhang/data/python/vision-web-service/vision/__init__.py", line 34, in __init__
    self.boxes, self.scores, self.classes = self.generate()
  File "/home/tonyzhang/data/python/vision-web-service/vision/__init__.py", line 66, in generate
    num_anchors/len(self.yolo_model.output) * (num_classes + 5), \
TypeError: object of type 'Tensor' has no len()
可以提供一下model.h5这个文件吗，一直跑不起来

**Comment by silencesmile** [comment]
想要你的h5文件，其他的我也都没跑起来
